spring.application.name=tracker-server

spring.datasource.url=${TIDB_URL}
spring.datasource.username=${TIDB_USER}
spring.datasource.password=${TIDB_PASSWORD}

jwt.secret=MahendarTrackerSecretKeyMahendarTrackerSecretKey12345
jwt.expiration=${JWT_EXPIRE}

# 1. Tell Spring Boot to load your .env file safely
#spring.config.import=optional:file:.env[.properties]

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=${PORT:8080}

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true